server:
    port: 8500  # Port on which the application will run

spring:
  mvc:
    view:
        prefix: WEB-INF/views/
        suffix: .jsp
  servlet:
    multipart:
      enabled: true  # Enable multipart support for file uploads
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
logging:
  level:
    root: INFO  # Set the logging level for the root logger
    org.springframework.web: INFO  # Set the logging level for Spring Web
gemini:
  api:
    endpoint: https://generativelanguage.googleapis.com/v1beta/models/ # Gemini API endpoint
    key: ${GEMINI_API_KEY}  # Gemini API key from environment variable